# Generated by Django 6.1.2 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=254)),
                ('ccity', models.CharField(max_length=100)),
            ],
        ),
    ]
